variables:
  PROJECT_PATH: medium-articles/todo-app

include:
  - local: 'gitlab/ci-cd/cicd-templates.yml'

stages:
  - test
  - coverage
  - build

# The jobs from cicd-templates.yml will be included here

# Build the application
build:
  stage: build
  image: maven:3.8.1-openjdk-11-slim
  script:
    - cd medium-articles/todo-app
    - mvn clean package -s settings.xml
  artifacts:
    paths:
      - medium-articles/todo-app/target/todo-app.war
  rules:
    - if: $CI_COMMIT_BRANCH