include:
  - local: 'ci-cd/*.yml'

stages:
  - pre-build
  - test
  - build

# Run tests
test:
  stage: test
  image: maven:3.8.1-openjdk-11-slim
  script:
    - cd medium-articles/todo-app
    - mvn test
  artifacts:
    reports:
      junit: medium-articles/todo-app/target/surefire-reports/TEST-*.xml

# Build the application
build:
  stage: build
  image: maven:3.8.1-openjdk-11-slim
  script:
    - cd medium-articles/todo-app
    - mvn clean package -s settings.xml
  artifacts:
    paths:
      - medium-articles/todo-app/target/todo-app.war