apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    namespace: kube-system
    version: 0.9.18
    releaseName: external-secrets-operator
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - values.yaml