apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: {{ .Release.Name }}-db
    role: mysql
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
