apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-db
    role: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Release.Name }}-db
    role: mysql
