apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-db
    role: mysql
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
      role: mysql
  serviceName: {{ .Release.Name }}-mysql
  replicas: 1 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
        role: mysql
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.db.image }}:{{ .Values.db.tag }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "bash /opt/poststart.sh" ]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret-env
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-sql-scripts
          mountPath: /etc/population.sql
        - mountPath: /opt/poststart.sh
          subPath: poststart.sh
          name: mysql-bash-scripts
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-sql-scripts
        secret:
          secretName: {{ .Release.Name }}-secret-sql
      - name: mysql-bash-scripts
        secret:
          secretName: {{ .Release.Name }}-config
          defaultMode: 0755
