apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: python-demo-population-db
    role: mysql
  namespace: python-population-app
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
