apiVersion: v1
kind: Secret
metadata:
  name: python-demo-population-secret-env
  namespace: python-population-app
type: Opaque
data:
  password: cm9vdA==

apiVersion: v1
kind: Secret
metadata:
  name: python-demo-population-secret-sql
  namespace: python-population-app
type: Opaque
stringData:
  db.sql: |
    CREATE DATABASE Population;
    use Population;

    CREATE TABLE `country` (
      `id` int unsigned NOT NULL,
      `city` varchar(50) NOT NULL,
      `population` int NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    insert  into `country`(`id`,`city`,`population`) values
    (1,'Jakarta','30539000'),
    (2,'Delhi','24998000'),
    (3,'Manila','24123000'),
    (4,'Seoul-Incheon','23480000'),
    (5,'Shanghai','23416000'),
    (6,'Sao Paulo','20365000'),
    (7,'Mexico','20063000'),
    (8,'Moscow','16170000'),
    (9,'Los Angeles','15058000');
