kind: Kustomization

helmCharts:
  - repo: https://charts.gitlab.io
    name: gitlab-runner
    version: 0.66.0
    releaseName: gitlab-runner
    namespace: gitlab-runner
    valuesFile: values.yaml
    includeCRDs: true
