kind: Kustomization
resources:
- "./resources/externalsecret.yaml"
- "./resources/aws-secretstore.yaml"
- "./resources/gitlab-runner-config.yaml" 
- "./efs-provisioner.yaml"


helmCharts:
  - repo: https://charts.gitlab.io
    name: gitlab-runner
    version: 0.66.0
    releaseName: gitlab-runner
    namespace: gitlab-runner
    valuesFile: values.yaml
    includeCRDs: true

# this is to handle the account id for the annotation to assume role by gitlab runner
# this is not required if bash script not used and you can update annotation in values.yaml file

patches:
- patch: |-
    - op: replace
      path: /spec/values/serviceAccountAnnotations/eks.amazonaws.com~1role-arn
      value: $(ROLE_ARN)
  target:
    kind: HelmChart
    name: gitlab-runner

vars:
- name: ROLE_ARN
  objref:
    kind: ConfigMap
    name: gitlab-runner-config
    apiVersion: v1
  fieldref:
    fieldpath: data.role-arn
