kind: Kustomization
resources:
- "./resources/externalsecret.yaml"
- "./resources/aws-secretstore.yaml" 
- "./resources/efs-provisioner.yaml"

helmCharts:
  - repo: https://charts.gitlab.io
    name: gitlab-runner
    version: 0.66.0
    releaseName: gitlab-runner
    namespace: gitlab-runner
    valuesFile: values.yaml
    includeCRDs: true

replacements:
  - source:
      kind: ExternalSecret
      name: gitlab-runner-secret
      fieldPath: spec.data[?(@.secretKey=='efs-id')].remoteRef.property
    targets:
      - select:
          kind: StorageClass
          name: efs-sc
        fieldPaths:
          - parameters.fileSystemId
      - select:
          kind: HelmChart
          name: gitlab-runner
        fieldPaths:
          - spec.values.runners.config

  - source:
      kind: ExternalSecret
      name: gitlab-runner-secret
      fieldPath: spec.data[?(@.secretKey=='aws-account-id')].remoteRef.property
    targets:
      - select:
          kind: HelmChart
          name: gitlab-runner
        fieldPaths:
          - spec.values.rbac.serviceAccountAnnotations.eks\.amazonaws\.com/role-arn