apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-runner
resources:
  - https://gitlab.com/gitlab-org/charts/gitlab-runner/-/raw/main/values.yaml
patchesStrategicMerge:
  - values.yaml