apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
spec:
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
    refreshInterval: 30s
  target:
    name: gitlab-runner-secrets
    creationPolicy: Owner
  data:
  - secretKey: runner-registration-token
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: runner-registration-token
  - secretKey: runner-token
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: runner-token