apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
spec:
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: gitlab-runner-secrets
    creationPolicy: Owner
  data:
  - secretKey: runner-registration-token
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: runner-registration-token
  - secretKey: runner-token
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: runner-token
  # you dont need these two secret if you not using bash script to provision runner directly update kustomization and values.yaml file
  - secretKey: aws-account-id
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: aws-account-id
  - secretKey: efs-id
    remoteRef:
      key: gitlab/gitlab-runner-secrets
      property: efs-id