apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  aws-account-id: "${AWS_ACCOUNT_ID}"
  role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/GitlabRunnerServiceAccountRole"
  efs-id: "${EFS_ID}"