AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance with Admin role for EKS management'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t3.small, t3.medium]
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AdminInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref AdminRole

  AdminInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dcc1e21636832c5d  # Amazon Linux 2 AMI (adjust for your region)
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref AdminInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y aws-cli
          amazon-linux-extras install docker
          service docker start
          usermod -a -G docker ec2-user
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          mv /tmp/eksctl /usr/local/bin
      Tags:
        - Key: Name
          Value: EKS-Admin-Instance

Outputs:
  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref AdminInstance
  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt AdminInstance.PublicDnsName
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt AdminInstance.PublicIp