AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Kubernetes ServiceAccount for GitLab Runner

Parameters:
  EksClusterName:
    Type: String
    Description: Name of the EKS cluster

Resources:
  GitLabRunnerServiceAccount:
    Type: 'Custom::AWSEKS_KubernetesResource'
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:eksctl-${EksClusterName}-addon-iamserviceaccount'
      ClusterName: !Ref EksClusterName
      Manifest: !Sub |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: gitlab-runner-sa
          namespace: gitlab-runner
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::${AWS::AccountId}:role/GitLabRunnerRole

Outputs:
  ServiceAccountName:
    Description: Name of the created Kubernetes ServiceAccount
    Value: gitlab-runner-sa