---
include:
  - local: 'gitlab/ci-cd/unit-tests.yml'
  - local: 'gitlab/ci-cd/secret-detection.yml'
  - local: 'gitlab/ci-cd/sast.yml'
  - local: 'gitlab/ci-cd/code-coverage.yml'
  - local: 'gitlab/ci-cd/vulnerability-scan.yml'

stages:
  - test
  - build

variables:
  PROJECT_PATH: ${PROJECT_PATH:-./}

.test_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

unit_tests:
  extends: 
    - .unit_tests
    - .test_rules

secret_detection:
  extends:
    - .secret_detection
    - .test_rules

sast:
  extends:
    - .sast
    - .test_rules

code-coverage:
  extends:
    - .code_coverage
    - .test_rules

vulnerability-scan:
  extends:
    - .vulnerability_scan
    - .test_rules